### ISSUE TITLE
Crash during install

### ISSUE THREAD

**Issue by caniko** [GoXLR-on-Linux/goxlr-on-linux#28]
**Describe the bug**
I get the following error when trying to install the file:
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
```

**To Reproduce**
Steps to reproduce the behavior, execute: `sudo sh install.sh`

**Expected behavior**
Full log:
```
Cloning into 'goxlr-on-linux'...
remote: Enumerating objects: 276, done.
remote: Counting objects: 100% (276/276), done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 276 (delta 158), reused 105 (delta 52), pack-reused 0
Receiving objects: 100% (276/276), 54.87 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (158/158), done.
warning: jack2-1.9.18-2 is up to date -- reinstalling
warning: jack2-dbus-1.9.18-2 is up to date -- reinstalling
warning: pulseaudio-jack-14.2-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) jack2-1.9.18-2  jack2-dbus-1.9.18-2  pulseaudio-jack-14.2-3

Total Installed Size:  2.81 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 pulseaudio-jack-14.2-3-x86_64 is up to date
(3/3) checking keys in keyring                               [################################] 100%
(3/3) checking package integrity                             [################################] 100%
(3/3) loading package files                                  [################################] 100%
(3/3) checking for file conflicts                            [################################] 100%
(3/3) checking available disk space                          [################################] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
Using system disk as snapshot device for creating snapshots in BTRFS mode

/dev/nvme0n1p6 is mounted at: /run/timeshift/backup, options: rw,relatime,compress=zstd:3,ssd,space_cache,autodefrag,subvolid=5,subvol=/

Creating new backup...(BTRFS)
Saving to device: /dev/nvme0n1p6, mounted at path: /run/timeshift/backup
Created directory: /run/timeshift/backup/timeshift-btrfs/snapshots/2021-07-05_17-44-08
Created subvolume snapshot: /run/timeshift/backup/timeshift-btrfs/snapshots/2021-07-05_17-44-08/@
Created control file: /run/timeshift/backup/timeshift-btrfs/snapshots/2021-07-05_17-44-08/info.json
BTRFS Snapshot saved successfully (0s)
Tagged snapshot '2021-07-05_17-44-08': ondemand
------------------------------------------------------------------------------

/dev/nvme0n1p6 is mounted at: /run/timeshift/backup, options: rw,relatime,compress=zstd:3,ssd,space_cache,autodefrag,subvolid=5,subvol=/

------------------------------------------------------------------------------
Removing snapshot: 2021-07-02_09-26-55
Deleting subvolume: @ (Id:685)
Deleted subvolume: @ (Id:685)

Destroying qgroup: 0/685
Destroyed qgroup: 0/685

Deleted directory: /run/timeshift/backup/timeshift-btrfs/snapshots/2021-07-02_09-26-55
Removed snapshot: 2021-07-02_09-26-55
------------------------------------------------------------------------------
Generating grub configuration file ...
Found theme: /boot/grub/themes/starfield/theme.txt
Found linux image: /boot/vmlinuz-linux-zen
Found initrd image: /boot/amd-ucode.img /boot/initramfs-linux-zen.img
Found fallback initrd image(s) in /boot:  amd-ucode.img initramfs-linux-zen-fallback.img
Found linux image: /boot/vmlinuz-linux-tkg-bmq
Found initrd image: /boot/amd-ucode.img /boot/initramfs-linux-tkg-bmq.img
Found fallback initrd image(s) in /boot:  amd-ucode.img initramfs-linux-tkg-bmq-fallback.img
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
Detecting snapshots ...
Info: Separate boot partition detected
Found snapshot: 2021-07-05 17:44:08 | timeshift-btrfs/snapshots/2021-07-05_17-44-08/@
Found snapshot: 2021-07-05 17:20:20 | timeshift-btrfs/snapshots/2021-07-05_17-20-20/@
Found snapshot: 2021-07-05 09:22:28 | timeshift-btrfs/snapshots/2021-07-05_09-22-28/@
Found snapshot: 2021-07-05 09:17:12 | timeshift-btrfs/snapshots/2021-07-05_09-17-12/@
Found snapshot: 2021-07-04 21:00:01 | timeshift-btrfs/snapshots/2021-07-04_21-00-01/@
Found snapshot: 2021-07-03 21:00:01 | timeshift-btrfs/snapshots/2021-07-03_21-00-01/@
Found snapshot: 2021-07-03 18:02:00 | timeshift-btrfs/snapshots/2021-07-03_18-02-00/@
Found snapshot: 2021-07-02 21:00:01 | timeshift-btrfs/snapshots/2021-07-02_21-00-01/@
Found snapshot: 2021-02-16 22:50:16 | timeshift-btrfs/snapshots/2021-02-16_22-50-16/@
Found 9 snapshot(s)
Found memtest86+ image: /boot/memtest86+/memtest.bin
/usr/bin/grub-probe: warning: unknown device type nvme0n1.
done
:: Processing package changes...
(1/3) reinstalling jack2                                     [################################] 100%
(2/3) reinstalling jack2-dbus                                [################################] 100%
(3/3) reinstalling pulseaudio-jack                           [################################] 100%
:: Running post-transaction hooks...
(1/8) Syncing all file systems...
(2/8) Arming ConditionNeedsUpdate...
(3/8) Foreign/AUR package notification
brave-browser-nightly 1.22.30-1
it87-dkms-git 154.b159857-1
kwin-lowlatency 5.21-1
ledger-live 2.29.0-2
libalpm12 12.0.2-1
torguard 4.7.0-1
(4/8) Orphaned package notification...
mono 6.12.0.122-1
(5/8) Checking for .pacnew and .pacsave files...
(6/8) Updating pkgfile database...
(7/8) Checking which packages need to be rebuilt
(8/8) Syncing all file systems...
E: [pulseaudio] main.c: Failed to kill daemon: No such process
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 403, in <module>
    sys.exit(main())
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?
```

**Desktop (please complete the following information):**
 - OS: Garuda (Arch)

**Comment by lm41** [comment]
Can you try `xeyes` in command line?
